# Site settings
title: MSRA Shanghai AI/ML Group
description: "Introduction of the research and news of MSRA Shanghai AI/ML Group."
url: "https://shanghai-ai-ml.github.io"
author:
  name: "MSRA Shanghai AI/ML Group"
  email: "dongsli@microsoft.com"
  url: "https://shanghai-ai-ml.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: true
custom_nav_footer: false
reverse: false
